askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from blog import views as blog_views
from webtoon import views as webtoon_views

# def root(request):
#     return redirect('post_list')

urlpatterns = [
    # url(r'^$', root),
    url(r'^$', lambda request: redirect('blog:post_list')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),  # namespace 를 걸지않습니다.
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^webtoon/', include('webtoon.urls', namespace='webtoon')),
    url(r'^game/', include('game.urls', namespace='game')),
    url(r'^journal/', include('journal.urls', namespace='journal')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.conf.urls import url
from blog import views
from blog import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),   # TODO: + comment_list
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^(?P<post_pk>\d+)/comments/$', views.comment_list, name='comment_list'),
    url(r'^(?P<post_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
]

blog/models.py
import os
import uuid
import re
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import MinLengthValidator
from django.db import models
from django.forms import ValidationError
from django.utils import timezone


def random_name_upload_to(instance, filename):
    name = uuid.uuid4().hex
    ext = os.path.splitext(filename)[-1].lower()
    # datetime.datetime.now() # XXX
    dir_path = timezone.now().strftime('%Y')  #/%m/%d/%H')
    return os.path.join(dir_path, name[:2], name[2:4], name[4:] + ext)
    # return os.path.join(dir_path, name + ext)


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')


class Post(models.Model):
    user = models.ForeignKey(User, related_name='blog_post_set')
    author = models.CharField(max_length=20)
    title = models.CharField(max_length=100,
            validators=[MinLengthValidator(10)],
            verbose_name='제목', help_text='포스팅 제목으로 노출됩니다. 최대 100자까지 지원됩니다.')  # descriptor syntax
    content = models.TextField(verbose_name='내용')
    photo = models.ImageField(upload_to=random_name_upload_to)
    lnglat = models.CharField(max_length=50, blank=True,
            validators=[lnglat_validator])
    tag_set = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.pk])

    def lat(self):
        if self.lnglat:
            return self.lnglat.split(',')[-1]
        return None

    def lng(self):
        if self.lnglat:
            return self.lnglat.split(',')[0]
        return None


class Comment(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()

    class Meta:
        ordering = ['-id']


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['author', 'title', 'content', 'photo']

    def clean_title(self):
        title = self.cleaned_data.get('title', '')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content', '')
        if len(content) % 2 == 0:
            # raise forms.ValidationError('홀수 길이로 입력하세요.')
            self.add_error('content', '홀수 길이로 입력하세요.')
        content = ' '.join(word for word in content.split())
        return content

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']
        widgets = {
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

blog/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm


def post_list(request):
    return render(request, 'blog/post_list.html', {
        'post_list': Post.objects.all(),
    })


def post_detail(request, pk):
#   try:
#       post = Post.objects.get(pk=pk)  # Post.DoesNotExist, Post.MultipleObjectsReturned
#   except (Post.DoesNotExist, Post.MultipleObjectsReturned):
#       raise Http404   # django.http.Http404

    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()

    return render(request, 'blog/post_detail.html', {
        'post': post,
        'comment_form': comment_form,
    })


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            print('통과한 값 : ', form.cleaned_data)
            # return redirect(post)
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.info(request, '포스팅을 잘 저장했습니다.')
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            print('통과한 값 : ', form.cleaned_data)
            # return redirect(post)
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            messages.info(request, '포스팅을 잘 저장했습니다.')
            return redirect(post)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form,
    })


def comment_list(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    return render(request, 'blog/_comment_list.html', {
        'comment_list': post.comment_set.all(),
    })


@login_required
def comment_new(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES)
        if form.is_valid():
            # form.cleaned_data
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            if request.is_ajax():
                return render(request, 'blog/_comment.html', {
                    'comment': comment,
                })
            messages.success(request, '새 댓글을 저장했습니다.')
            return redirect(comment.post)
    else:
        form = CommentForm()

    return render(request, 'blog/comment_form.html', {
        'form': form,
    })


@login_required
def comment_edit(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if comment.user != request.user:
        messages.warning(request, '댓글 작성자만 수정할 수 있습니다.')
        return redirect(comment.post)

    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save()
            if request.is_ajax():
                return render(request, 'blog/_comment.html', {
                    'comment': comment,
                })
            messages.success(request, '기존 댓글을 수정했습니다.')
            return redirect(comment.post)
    else:
        form = CommentForm(instance=comment)

    if request.is_ajax():
        template_name = '_modal_form.html'
    else:
        template_name = 'blog/comment_form.html'

    return render(request, template_name, {
        'form': form,
    })


@login_required
def comment_delete(request, post_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if comment.user != request.user:
        messages.warning(request, '댓글 작성자만 삭제할 수 있습니다.')
        return redirect(comment.post)

    if request.method == 'POST':
        comment.delete()
        messages.success(request, '댓글을 삭제했습니다.')
        return redirect(comment.post)
    return render(request, 'blog/comment_confirm_delete.html', {
        'comment': comment,
    })

blog/templates/blog/_comment.html
<li id="comment-{{ comment.pk }}">
    {{ comment.message }}
    <small>by {{ comment.user }}</small>

    {% if comment.user == user %}
        <a href="{% url "blog:comment_edit" comment.post.pk comment.pk %}" class="ajax-modal-form" data-target-id="comment-{{ comment.pk }}">Edit</a>
        <a href="{% url "blog:comment_delete" comment.post.pk comment.pk %}" class="text-danger ajax-confirm" data-message="정말 삭제하시겠습니까?" data-target-id="comment-{{ comment.pk }}">Delete</a>
    {% endif %}
</li>

blog/templates/blog/_comment_list.html
{% for comment in comment_list %}
    {% include "blog/_comment.html" %}
{% endfor %}

blog/templates/blog/comment_confirm_delete.html
{% extends "blog/layout.html" %}

{% block content %}

    <form action="" method="post">
        {% csrf_token %}

        <p class="alert alert-danger">정말 삭제하시겠습니까? </p>

        <a href="{{ comment.post.get_absolute_url }}" class="btn btn-default">취소하겠소.</a>
        <input type="submit" value="진심입니다." class="btn btn-danger" />
    </form>

{% endblock %}

blog/templates/blog/comment_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            {{ form.as_table }}
        </table>
        <input type="submit" />
    </form>
{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}
{% load staticfiles %}

{% block extra_head %}
{# <link rel="stylesheet" href="{% static "blog/style.css" %}" /> #}
    {{ block.super }}
{% endblock %}

{% block window_title %}AskDjango 블로그{% endblock %}

{% block title %}AskDjango 블로그{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}

{% block extra_head %}
    {{ block.super }}
<script>
function initMap() {
    var $map = $('#map');

    if ( $map.size() > 0 ) {
        var lat = $map.data('lat');
        var lng = $map.data('lng');

        var myLatLng = {'lat': lat, 'lng': lng};

        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 7,
            center: myLatLng
        });

        var marker = new google.maps.Marker({
            position: myLatLng,
            map: map,
            title: 'Hello World!'
        });
    }
}
</script>
<script async defer
        src="https://maps.googleapis.com/maps/api/js?callback=initMap"></script>
{% endblock %}

{% block content %}
    <h2>{{ post.title }}</h2>

    <ul>
        <li>
            Tags :
            {% for tag in post.tag_set.all %}
                {{ tag.name }}
            {% endfor %}
        </li>
    </ul>

    {% if post.lnglat %}
        <div id="map" data-lat="{{ post.lat }}" data-lng="{{ post.lng }}"></div>
    {% endif %}

    {% if post.photo %}
        <img src="{{ post.photo.url }}" style="max-width: 100%;" />
    {% endif %}

    {{ post.content|linebreaks }}

    <hr/>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#ajax-comment-modal">
        Ajax로 댓글 쓰기
    </button>

    <!-- Modal -->
    <div class="modal fade" id="ajax-comment-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">

        <form id="ajax_comment_form" action="{% url "blog:comment_new" post.pk %}" method="post">
            {% csrf_token %}

            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">댓글 쓰기</h4>
                    </div>
                    <div class="modal-body">
                        {{ comment_form.message }}
                    </div>
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-primary" value="저장" />
                    </div>
                </div>
            </div>
        </form>
    </div>

    <script>
        $(function() {
            $('#ajax_comment_form').ajaxForm(function(html) {
                $('#comment_list').prepend(html);
                $('#ajax_comment_form')[0].reset();
                $('#ajax-comment-modal').modal('hide');
            });
        });
    </script>

    <hr/>

    {% comment %}
    <form id="comment_form" action="{% url "blog:comment_new" post.pk %}" method="post">
        {% csrf_token %}
        {{ comment_form.message }}
        <input type="submit" class="btn btn-primary btn-block" value="댓글 쓰기" />
    </form>
    <script>
        $(function() {
            $('#comment_form').ajaxForm(function(html) {
                $('#comment_list').prepend(html);
                $('#comment_form')[0].reset();
            });
        });
    </script>
    {% endcomment %}

    <!--
    <a href="{% url "blog:comment_new" post.pk %}" class="btn btn-primary btn-block">댓글쓰기</a>
    -->

    <ul id="comment_list">
        {% include "blog/_comment_list.html" with comment_list=post.comment_set.all %}
    </ul>

    <a href="{% url "blog:comment_list" post.pk %}" class="btn btn-default btn-block ajax-load" data-target-id="comment_list">댓글 새로고침</a>

    <hr/>
    <a href="{% url "blog:post_list" %}" class="btn btn-default">목록</a>
    <a href="{% url "blog:post_edit" post.pk %}" class="btn btn-primary">수정</a>

{% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/layout.html" %}

{% block content %}
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <table class="table table-bordered table-hover">
            {{ form }}
        </table>
        <input type="submit" class="btn btn-primary btn-block" />
    </form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <ul>
    {% for post in post_list %}
        <li>
            [{{ post.pk }}]
            <a href="/blog/{{ post.pk }}/">
                {{ post.title }}
            </a>
            <a href="{% url "blog:post_detail" post.pk %}">
                URL Reverse #1
            </a>
            <a href="{{ post.get_absolute_url }}">
                URL Reverse #2
            <a/>
            <small>at {{ post.updated_at }}</small>
        </li>
    {% endfor %}
    </ul>
    <hr/>
    <a href="{% url "blog:post_new" %}" class="btn btn-primary">새 글 쓰기</a>
{% endblock %}