askdjango/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from blog import views as blog_views
from webtoon import views as webtoon_views

# def root(request):
#     return redirect('post_list')

urlpatterns = [
    # url(r'^$', root),
    url(r'^$', lambda request: redirect('blog:post_list')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),  # namespace 를 걸지않습니다.
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^webtoon/', include('webtoon.urls', namespace='webtoon')),
    url(r'^game/', include('game.urls', namespace='game')),
    url(r'^journal/', include('journal.urls', namespace='journal')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
from django.conf.urls import url
from blog import views
from blog import views_cbv

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),   # TODO: + comment_list
    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^(?P<post_pk>\d+)/comments/$', views.comment_list, name='comment_list'),
    url(r'^(?P<post_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<post_pk>\d+)/comments/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
]

journal/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^new/$', views.post_new, name='post_new'),
]

journal/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse('journal:post_detail', args=[self.pk])

journal/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

journal/views.py
from django.shortcuts import redirect, render
from .models import Post
from .forms import PostForm


def post_list(request):
    return render(request, 'journal/post_list.html', {
        'post_list': Post.objects.all(),
    })

def post_detail(request, pk):
    post = Post.objects.get(pk=pk)
    return render(request, 'journal/post_detail.html', {
        'post': post,
    })

def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            # post = Post.objects.create(**form.cleaned_data)
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'journal/post_form.html', {
        'form': form,
    })

journal/templates/journal/post_detail.html
<h1>{{ post.title }}</h1>

{{ post.content|linebreaks }}

<hr/>

<a href="{% url "journal:post_list" %}">글 목록</a>

journal/templates/journal/post_form.html
<form method="post">
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" />
</form>

journal/templates/journal/post_list.html
<ul>
{% for post in post_list %}
    <li>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </li>
{% empty %}
    <li>
        등록된 포스팅이 없습니다.
    </li>
{% endfor %}
</ul>

<hr/>

<a href="{% url "journal:post_new" %}">새 포스팅</a>

journal/templates/journal/post_new.html
<!DOCTYPE html>
<html>
<head>
    <title>
    </title>
</head>
<body>
Form
<form method ="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <input type="submit" />
</body>
</html>